Attempted to fix the Projection Upper band and lower band calculation
cinar/indicatorts pull request #329
Opened 2023-07-08 04:23 UTC by abhishekmittal15

Attempting to fix #218 

Modified the projection Oscillator function by changing the calculation of the arrays `pu` and `pl`. 
Hi @cinar ,
Please have a look at the code which has `LOOK HERE` written, that is the changes made to the implementation mainly. 
Let me know what you think about it.

The file is messy right now, I will clean it after you have approved the changes in the logic part of the code

Thanks

2023-08-13 07:35 UTC, abhishekmittal15 commented
Hi @cinar , I was wondering if you got a chance to have a look at the previous comment and the code?

Regards,
Abhishek Mittal

2023-08-14 21:59 UTC, cinar commented
My sincere apologies, I totally missed your earlier message. Let me quickly take a look.

2023-08-14 22:06 UTC, cinar requested changes
I added few comments. Thank you very much for your contribution!

2023-08-14 22:06 UTC, cinar commented on src/indicator/volatility/projectionOscillator.ts
> +function padWithZeros(desiredLength: number, arr: number[]) {
This is a very nice helper function to add to ../../helper/numArray probably?

2023-08-14 22:06 UTC, cinar commented on src/indicator/volatility/projectionOscillator.ts
> +    // for (let j = 0; j < period; j++) {
Shall we remove these comments?

2023-08-14 22:06 UTC, cinar commented on src/indicator/volatility/projectionOscillator.ts
> +    // for (let j = 0; j < period; j++) {
Shall we remove these comments?

2023-08-14 22:06 UTC, cinar commented on src/indicator/volatility/projectionOscillator.ts
> +  // const pu = mmax(period, vHighs);
Shall we remove these comments?

2023-08-14 22:06 UTC, cinar commented on src/indicator/volatility/projectionOscillator.ts
> +const closings = generateRandomNumbers(100, 30, 5);
I guess some test code got left over here?

2023-08-14 22:06 UTC, cinar commented on src/indicator/volatility/projectionOscillator.ts
> +function generateRandomNumbers(count: number, mean: number, stdDev: number) {
May be the function can be named differently to reflect how you are using the mean and stdDev? I guess they are not just random number right? Also would be nice to have this in ../../helper/numArray.ts as well.

2023-08-14 22:06 UTC, cinar commented on src/indicator/volatility/projectionOscillator.ts
> +const result = projectionOscillator(14, 5, highs, lows, closings);
Since you have a test case here, can we put it into the unit test?

2023-08-16 23:16 UTC, abhishekmittal15 commented
So @cinar , does the changes in the logic part make sense. Does the error in the previous version of the code and my fix make logical sense, or do you have any questions about it. 

Yes I will clean up the file, I just wanted to first confirm if the logic is right 😅 . 

Also is there some way to check if this implementation is actually giving the right values?

2023-08-17 17:04 UTC, cinar commented
I think your fix definitely makes sense. What we are lacking is a test case here. If we can find a source of truth for this calculation that we can compare the results against, it will give us more confidence that this is the correct algorithm to go with. Not sure if there is already an example that we can use, or an other tool to compute and compare the results against?

2026-09-03 02:02 UTC, cinar commented
Thank you for the contribution! We ended up fixing the underlying Projection Oscillator bug (dropped regression intercept) independently in #536, which is now merged, so closing this one out. Appreciate you flagging and attempting a fix back in 2023.

2026-09-03 02:02 UTC, closed without merging